name: Build and Upload

on:
  push:
    branches:
      - master

env:
  WEBAPP_NAME: Solution1.sln            # set this to your application's name
  WEBAPP_PACKAGE_PATH: 'published'      # set this to the path to your web app project, defaults to the repository root
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.1
      with:
        vs-version: "[16.4,16.9)"
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore ${{ env.WEBAPP_NAME }}

    - name: Build
      run: msbuild ${{ env.WEBAPP_NAME }} /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.WEBAPP_PACKAGE_PATH }}
        path: bin\Release\Publish
